[build]
  publish = "dist"
  command = "npm run build:netlify"
[build.processing.html]
  pretty_urls = false
[[headers]]
  for = "/_astro/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[build.environment]
  GITHUB_IMAGES = "true"
